flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post, Todo
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.bio = form.bio.data
        current_user.facebook = form.facebook.data
        current_user.twitter = form.twitter.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.bio.data = current_user.bio
        form.facebook.data = current_user.facebook
        form.twitter.data = current_user.twitter
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=6)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)





@users.route('/agenda', methods=['POST', 'GET'])
def agenda():
    if request.method == 'POST':
        task_content = request.form['content']
        new_task = Todo(content = task_content)
        db.session.add(new_task)
        db.session.commit()
        return redirect(url_for('users.agenda'))
    else:
        tasks = Todo.query.order_by(Todo.date_created).all()
        return render_template('agenda.html', tasks = tasks)



@users.route('/delete/<int:id>')
def delete(id):
    task_to_delete = Todo.query.get_or_404(id)

    try:
        db.session.delete(task_to_delete)
        db.session.commit()
        return redirect(url_for('users.agenda'))
    except:
        return 'There was a problem deleting that task'



@users.route('/update_task/<int:id>', methods=['GET', 'POST'])
def update_task(id):
    task = Todo.query.get_or_404(id)

    if request.method == 'POST':
        task.content = request.form['content']

        try:
            db.session.commit()
            return redirect(url_for('users.agenda'))
        except:
            return 'There was a issue updating your task'
            

    else:
        return render_template('update_task.html', task = task)

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}

<header>
    <a href="{{ url_for('main.home') }}">
        <img src="{{ url_for('static', filename='profile_pics/logo.jpg') }}" alt="logo" height="40">
    </a>
    <div class="header-right">
        {% if current_user.is_authenticated %}
        <nav>
            <ul>
                <li><a href="{{ url_for('main.home') }}">Home</a></li>
                <li><a href="{{ url_for('posts.new_post') }}">New Post</a></li>
                <li><a href="{{ url_for('users.agenda') }}">Agenda</a></li>
                <li><a href="{{ url_for('main.home') }}">Blog</a></li>
                <li><a href="#">Info</a></li>
                <li><a class="is-active" href="{{ url_for('users.account') }}">Account</a></li>
            </ul>
        </nav>
            <a href="{{ url_for('users.logout') }}" class="button red">logout</a>
        {% else %}
        <nav>
            <ul>
                <li><a href="{{ url_for('main.home') }}" class="is-active">Home</a></li>
            </ul>
        </nav>
            <a href="{{ url_for('users.login') }}" class="button blue">Login / Register</a>
        {% endif %}
    </div>
</header>   



<div class="daccount">
    <section class="dform">

        <div class="imes">
            <img class="rounded-circle account-img" src="{{ image_file }} " alt="default" width="320" height="400">
        </div>
    
        <div class="col5">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.bio }}</p>
            <p class="text-secondary">{{ current_user.email }}</p>
            <p><a href="current_user.facebook">{{ current_user.facebook }}</a></p>
            <p><a href="current_user.twitter">{{ current_user.twitter }}</a></p>
        </div>
    </section>

</div>

<div class="contenedor3">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="formulario">
            <legend class="border-bottom">Account Info</legend>

            <div class="col6">
                {{ form.username.label(class="form-control-label") }}
                <br><br><br><br>
                {{ form.bio.label(class="form-control-label") }}
                <br>
                {{ form.email.label(class="form-control-label") }}
                <br>
                {{ form.facebook.label(class="form-control-label") }}
                <br>
                {{ form.twitter.label(class="form-control-label") }}
                <br>
                {{ form.picture.label() }}
            </div>

            <div class="col7">
                {{ form.username(class="form-control form-control-lg", style="width:650px;") }}
                <br>
                {{ form.bio(class="form-control form-control-lg", rows="5", style="width:650px;") }}
                <br>
                {{ form.email(class="form-control form-control-lg", style="width:650px;") }}
                <br>
                {{ form.facebook(class="form-control form-control-lg", style="width:650px;") }}
                <br>
                {{ form.twitter(class="form-control form-control-lg", style="width:650px;") }}
                <br>
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}               
            </div>

        </fieldset>

        <div class="Abutton">
            <input type="submit" value="Update Profile" class="button blue">
        </div>

    </form>
</div>



{% endblock content %}

flaskblog/templates/agenda.html
{% extends "layout.html" %}
{% block content %}

<header>
    <a href="{{ url_for('main.home') }}">
        <img src="{{ url_for('static', filename='profile_pics/logo.jpg') }}" alt="logo" height="40">
    </a>
    <div class="header-right">
        {% if current_user.is_authenticated %}
        <nav>
            <ul>
                <li><a href="{{ url_for('main.home') }}">Home</a></li>
                <li><a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a></li>
                <li><a href="{{ url_for('users.agenda') }}" class="is-active">Agenda</a></li>
                <li><a href="{{ url_for('main.home') }}">Blog</a></li>
                <li><a href="#">Info</a></li>
                <li><a href="{{ url_for('users.account') }}">Account</a></li>
            </ul>
        </nav>
            <a href="{{ url_for('users.logout') }}" class="button red">logout</a>
        {% else %}
        <nav>
            <ul>
                <li><a href="{{ url_for('main.home') }}" class="is-active">Home</a></li>
            </ul>
        </nav>
            <a href="{{ url_for('users.login') }}" class="button blue">Login / Register</a>
        {% endif %}
    </div>
</header> 


<div class="content">
    <h1>Task Master</h1>
    {% if tasks|length < 1 %}
    <h4> There are no tasks. Create one below!</h4>

    {% else %}

    <table>
        <tr>
            <th> Task </th>
            <th> Added </th>
            <th> actions </th>
        </tr>

        {% for task in tasks %}

            <tr>
                <td>{{ task.content}}</td>
                <td>{{ task.date_created.date() }}</td>
                <td>
                    <a href="/delete/{{task.id}}"> Delete </a>
                    <br>
                    <a href="/update_task/{{task.id}}"> Update </a>
                </td>
            </tr>

        {% endfor %}

    </table>

    {% endif %}


    <div class="form">
        <form action="/agenda" method="POST">
            <input type="text" name="content" id="content">
            <input type="submit" value="Add Task">
        </form>
    </div>
</div>

{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}

<header>
    <a href="{{ url_for('main.home') }}">
        <img src="{{ url_for('static', filename='profile_pics/logo.jpg') }}" alt="logo" height="40">
    </a>
    <div class="header-right">
        {% if current_user.is_authenticated %}
        <nav>
            <ul>
                <li><a href="{{ url_for('main.home') }}" >Home</a></li>
                <li><a class="is-active" href="{{ url_for('posts.new_post') }}">New Post</a></li>
                <li><a href="{{ url_for('users.agenda') }}">Agenda</a></li>
                <li><a href="{{ url_for('main.home') }}">Blog</a></li>
                <li><a href="#">Info</a></li>
                <li><a href="{{ url_for('users.account') }}">Account</a></li>
            </ul>
        </nav>
            <a href="{{ url_for('users.logout') }}" class="button red">logout</a>
        {% else %}
        <nav>
            <ul>
                <li><a href="{{ url_for('main.home') }}" class="is-active">Home</a></li>
            </ul>
        </nav>
            <a href="{{ url_for('users.login') }}" class="button blue">Login / Register</a>
        {% endif %}
    </div>
</header>

<div class="contenedor">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="formulario">
            <legend class="border-bottom">{{ legend }}</legend>

            <div class="col3">
                {{ form.title.label(class="form-control-label") }}
                <br>
                {{ form.content.label(class="form-control-label") }}
            </div>

            <div class="col4">
                {{ form.title(class="form-control form-control-lg", style="width:850px;" ) }}
                <br>
                {{ form.content(class="form-control form-control-lg", rows="20", style="width:850px;") }}
            </div>

        </fieldset>

        <div class="Abutton">
            <input type="submit" value="Post" class="button blue">
        </div>

    </form>
</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}

    <header>
        <a href="{{ url_for('main.home') }}">
            <img src="{{ url_for('static', filename='profile_pics/logo.jpg') }}" alt="logo" height="40">
        </a>
        <div class="header-right">
            {% if current_user.is_authenticated %}
            <nav>
                <ul>
                    <li><a href="{{ url_for('main.home') }}" class="is-active">Home</a></li>
                    <li><a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a></li>
                    <li><a href="{{ url_for('users.agenda') }}">Agenda</a></li>
                    <li><a href="#blog-items">Blog</a></li>
                    <li><a href="#">Info</a></li>
                    <li><a href="{{ url_for('users.account') }}">Account</a></li>
                </ul>
            </nav>
                <a href="{{ url_for('users.logout') }}" class="button red">logout</a>
            {% else %}
            <nav>
                <ul>
                    <li><a href="{{ url_for('main.home') }}" class="is-active">Home</a></li>
                </ul>
            </nav>
                <a href="{{ url_for('users.login') }}" class="button blue">Login / Register</a>
            {% endif %}
        </div>
    </header>
    
    <section class="blog">

        <article class="portada">
            <img src="{{ url_for('static', filename='profile_pics/img1.jpg') }}" alt="img1" width="1000">
            <div class="description">
                {% for post in posts.items %}
                    {% if loop.index < 2 %}
                        <h1><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h1>
                        <div class="autor">
                            <p>
                                <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" 
                                alt="default" width="35px" height="35px"><span><a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></span>
                                <span>{{ post.date_posted.strftime('%Y-%m-%d') }}</span>
                            </p>
                        </div> 
                    {% endif %}
                {% endfor %}
            </div>
        </article>

        <div class="contenedor">
            <h2 class="titulo"> Entradas <span>Ante</span>riores</h2> <!--Sub-titulo-->   
        </div>

        <section id = "blog-items" class="blog-items">

            {% for post in posts.items %}

            <article class="item-blog">
                <a href="{{ url_for('posts.post', post_id=post.id) }}">
                    <img src="{{ url_for('static', filename='profile_pics/img6.jpg') }}" alt="img2" width="300" height="300">
                </a>
                <div class="description">
                    <h3><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
                    <div class="autor">
                        <p>
                            <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" 
                            alt="default" width="35px" height="35px"><span><a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></span>
                        </p>
                        <span>{{ post.date_posted.strftime('%Y-%m-%d') }}</span>
                    </div> 
                </div>                
            </article>

            {% endfor %}

        </section>
    </section>
 
    <div class="paginador">
        <ul>
            {% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
                {% if page_num %}
                    {% if posts.page == page_num %}
                        <li><a href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
                    {% else %}
                        <li><a href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </ul>
    </div>

{% endblock content %}

flaskblog/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400,600,700|Allerta" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='estilo.css') }}">
</head>
<body>
    
    <div class="section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom "> Log In </legend>
                
                <div class="form-group ">
                    {{ form.email.label(class="form-control-label", style="width:250px;") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}  
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %} 
                </div>

                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>

            </fieldset>

            <input type="submit" value="Sign in" class="button blue">
            
            <small>
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                <p>Need An Account? <a class="" href="{{ url_for('users.register') }}">Sign Up Now</a> </p> 
            </small>

        </form>
    </div> 

</body>
</html>

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}

    <header>
        <a href="{{ url_for('main.home') }}">
            <img src="{{ url_for('static', filename='profile_pics/logo.jpg') }}" alt="logo" height="40">
        </a>
        <div class="header-right">
            {% if current_user.is_authenticated %}
            <nav>
                <ul>
                    <li><a href="{{ url_for('main.home') }}">Home</a></li>
                    <li><a href="{{ url_for('posts.new_post') }}">New Post</a></li>
                    <li><a href="{{ url_for('users.agenda') }}">Agenda</a></li>
                    <li><a class="is-active" href="{{ url_for('main.home') }}">Blog</a></li>
                    <li><a href="#">Info</a></li>
                    <li><a href="{{ url_for('users.account') }}">Account</a></li>
                </ul>
            </nav>
                <a href="{{ url_for('users.logout') }}" class="button red">logout</a>
            {% else %}
            <nav>
                <ul>
                    <li><a href="{{ url_for('main.home') }}" class="is-active">Home</a></li>
                </ul>
            </nav>
                <a href="{{ url_for('users.login') }}" class="button blue">Login / Register</a>
            {% endif %}
        </div>
    </header>  


    <div class="formulario">

        <div class="col3">
            <img src="{{ url_for('static', filename='profile_pics/img6.jpg') }}" alt="img6" width="400" height="400">
        </div>


        <div class="description">
            <h3>{{ post.title }}</h3>
            <p class="article-content">{{ post.content }}</p>
            <div class="autor">
                <p>
                    <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" 
                        alt="default" width="35px" height="35px"><span>
                        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></span>
                </p>
                <span>{{ post.date_posted.strftime('%Y-%m-%d') }}</span>
            </div> 
            <nav>
                <ul>
                    {% if post.author == current_user %}
                    <li><a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="button red">Update</a></li>
                    <li><form action="{{ url_for('posts.delete_post', post_id=post.id)  }}" method=POST> <input class="button red" type="submit" value="Delete"></li>
                    {% endif %}
                </ul>
            </nav>
        </div>                
    </div>

{% endblock content %}

flaskblog/templates/update_task.html
{% extends "layout.html" %}

{% block content %}

<header>
    <a href="{{ url_for('main.home') }}">
        <img src="{{ url_for('static', filename='profile_pics/logo.jpg') }}" alt="logo" height="40">
    </a>
    <div class="header-right">
        {% if current_user.is_authenticated %}
        <nav>
            <ul>
                <li><a href="{{ url_for('main.home') }}">Home</a></li>
                <li><a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a></li>
                <li><a href="{{ url_for('users.agenda') }}" class="is-active">Agenda</a></li>
                <li><a href="#blog-items">Blog</a></li>
                <li><a href="#">Info</a></li>
                <li><a href="{{ url_for('users.account') }}">Account</a></li>
            </ul>
        </nav>
            <a href="{{ url_for('users.logout') }}" class="button red">logout</a>
        {% else %}
        <nav>
            <ul>
                <li><a href="{{ url_for('main.home') }}" class="is-active">Home</a></li>
            </ul>
        </nav>
            <a href="{{ url_for('users.login') }}" class="button blue">Login / Register</a>
        {% endif %}
    </div>
</header> 


<div class="content">
    <h1>Update Task</h1>

    <div class="form">
        <form action="/update_task/{{task.id}}" method="POST">
            <input type="text" name="content" id="content" value="{{task.content}}">
            <input type="submit" value="Update Task">
        </form>
    </div>
</div>

{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}

    <header>
        <a href="{{ url_for('main.home') }}">
            <img src="{{ url_for('static', filename='profile_pics/logo.jpg') }}" alt="logo" height="40">
        </a>
        <div class="header-right">
            {% if current_user.is_authenticated %}
            <nav>
                <ul>
                    <li><a href="{{ url_for('main.home') }}" class="is-active">Home</a></li>
                    <li><a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a></li>
                    <li><a href="{{ url_for('users.agenda') }}">Agenda</a></li>
                    <li><a href="#blog-items">Blog</a></li>
                    <li><a href="#">Info</a></li>
                    <li><a href="{{ url_for('users.account') }}">Account</a></li>
                </ul>
            </nav>
                <a href="{{ url_for('users.logout') }}" class="button red">logout</a>
            {% else %}
            <nav>
                <ul>
                    <li><a href="{{ url_for('main.home') }}" class="is-active">Home</a></li>
                </ul>
            </nav>
                <a href="{{ url_for('users.login') }}" class="button blue">Login / Register</a>
            {% endif %}
        </div>
    </header>
    
    <section class="blog">

        <div class="contenedor">
            <h2 class="titulo"> Entradas <span>Ante</span>riores de {{ user.username }} ({{ posts.total }}) </h2>   
        </div> <h1 class="mb-3">


        <div class="daccount">
            <section class="dform">
        
                <div class="imes">
                    <img src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}" 
                        alt="default" width="320" height="400">
                </div>
            
                <div class="col5">
                    <h2 class="account-heading">{{ user.username }}</h2>
                    <p class="text-secondary">{{ user.bio }}</p>
                    <p class="text-secondary">{{ user.email }}</p>
                    <p><a href="current_user.facebook">{{ user.facebook }}</a></p>
                    <p><a href="current_user.twitter">{{ user.twitter }}</a></p>
                </div>
            </section>
        
        </div>


        <section id = "blog-items" class="blog-items">

            {% for post in posts.items %}

            <article class="item-blog">
                <a href="{{ url_for('posts.post', post_id=post.id) }}">
                    <img src="{{ url_for('static', filename='profile_pics/img6.jpg') }}" alt="img2" width="300" height="300">
                </a>
                <div class="description">
                    <h3><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
                    <div class="autor">
                        <p>
                            <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" 
                            alt="default" width="35px" height="35px"><span><a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></span>
                        </p>
                        <span>{{ post.date_posted.strftime('%Y-%m-%d') }}</span>
                    </div> 
                </div>                
            </article>

            {% endfor %}

        </section>
    </section>
    
    <div class="paginador">
        <ul>
            {% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
                {% if page_num %}
                    {% if posts.page == page_num %}
                        <li><a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
                    {% else %}
                        <li><a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </ul>
    </div>

{% endblock content %}